import express from 'express';

// instantiate the server
const app = express();

// this tells our app to listen for GET messages on the '/' path
// the callback function specifies what the server will do when a message is received

app.get('/', (req, res) => {
	console.log(req);
	console.log(res);  // this will show the default response object generated by Express. We can modify or add to this object before calling res.send()
	res.send('Hello!');
});

app.post('/submit-data', (req, res) => {
	res.send('Received a POST request.');
});

app.get('/greeting',(req, res) => {
	res.send('Hello '+req.query.name);
	console.log(req);
});

// this tells our server to listen to the port 3000
// we can also pass an optional callback function to execute after the server starts
app.listen(3000, () => { console.log('Server started at port 3000')} );